# Build new image depending on python image latest
FROM ubuntu:latest

# Identify the maintainer of the image
LABEL version="0.0.1"
LABEL maintainer="godric.phoenix@gmail.com"

# Install required dependencies
RUN apt-get update && \
    apt-get install -y wget  iputils-ping dnsutils net-tools vim systemd alien libaio1 python3 python3-pip unixodbc odbcinst unzip libsasl2-dev python3-dev libldap2-dev libssl-dev build-essential libkrb5-dev && \
    rm -rf /var/lib/apt/lists/*

# Set ACCEPT_EULA environment variable
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=P@ssw0rd

# Download the Oracle Instant Client RPM package
RUN wget https://download.oracle.com/otn_software/linux/instantclient/2113000/oracle-instantclient-basic-21.13.0.0.0-1.el8.x86_64.rpm \
    --header="Cookie: oraclelicense=accept-securebackup-cookie" \
    -O /tmp/oracle-instantclient-basic-21.13.0.0.0-1.x86_64.rpm

# Install the RPM package using alien
RUN alien -i /tmp/oracle-instantclient-basic-21.13.0.0.0-1.x86_64.rpm --scripts && \
    rm -f /tmp/oracle-instantclient-basic-21.13.0.0.0-1.x86_64.rpm

# Set up environment variables
ENV LD_LIBRARY_PATH=/usr/lib/oracle/21/client64/lib:$LD_LIBRARY_PATH
ENV PATH=/usr/lib/oracle/21/client64/bin:$PATH

# Set up environment variables for Python
ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

# Download the ODBC driver package
# RUN wget https://packages.microsoft.com/ubuntu/22.10/prod/pool/main/m/msodbcsql18/msodbcsql18_18.2.1.1-1_amd64.deb -O /tmp/msodbcsql18_18.2.1.1-1_amd64.deb

# Install the ODBC driver for SQL Server
RUN apt-get update && \
    apt-get install -y \
        apt-transport-https \
        gnupg \
        curl && \
    # Add Microsoft package key
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    # Add Microsoft repository configuration
    curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && \
    # Install ODBC driver and related tools
    ACCEPT_EULA=Y apt-get install -y unixodbc jq msodbcsql18 mssql-tools18 unixodbc-dev -y

# Set up ODBC configuration
RUN echo "[ODBC Driver 22 for SQL Server]" >> /etc/odbcinst.ini && \
    echo "Description = Microsoft ODBC Driver 22 for SQL Server" >> /etc/odbcinst.ini && \
    # Verify that the driver path is correct for the installed version
    echo "Driver = /opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.3.so.2.1" >> /etc/odbcinst.ini && \
    echo "UsageCount = 1" >> /etc/odbcinst.ini


# Set up environment variables for ODBC Driver
ENV ODBCINI=/etc/odbc.ini
ENV ODBCSYSINI=/etc

# Download and install required dependencies for Google Chrome
RUN apt-get update && \
    apt-get install -y \
        fonts-liberation \
        libasound2 \
        libatk-bridge2.0-0 \
        libatk1.0-0 \
        libatspi2.0-0 \
        libcairo2 \
        libcups2 \
        libcurl4 \
        libdrm2 \
        libgbm1 \
        libglib2.0-0 \
        libgtk-3-0 \
        libnspr4 \
        libnss3 \
        libpango-1.0-0 \
        libu2f-udev \
        libvulkan1 \
        libxcomposite1 \
        libxdamage1 \
        libxext6 \
        libxfixes3 \
        libxkbcommon0 \
        libxrandr2 \
        xdg-utils && \
    rm -rf /var/lib/apt/lists/*

# Download and install Google Chrome
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O /tmp/google-chrome-stable_current_amd64.deb && \
    apt-get install -y /tmp/google-chrome-stable_current_amd64.deb && \
    rm -f /tmp/google-chrome-stable_current_amd64.deb

# Download chromedriver and move it to /usr/local/bin
RUN wget https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.69/linux64/chrome-linux64.zip -O /tmp/chromedriver_linux64.zip && \
    unzip -o /tmp/chromedriver_linux64.zip -d /usr/local/bin && \
    rm -f /tmp/chromedriver_linux64.zip


# Create  a directory for our application code and set it as
RUN  mkdir /app 

# Set work directory to /app
WORKDIR /app

# Add requirements.txt file to the container
ADD ./requirements.txt /app/

# Install all dependencies listed in requirements.txt
RUN pip3 install --upgrade pip && pip3 install --no-cache-dir -r requirements.txt

# Copy the rest of the project's
ADD ./app.py /app/

# Configure Kerberos authentication
COPY krb5.conf /etc/krb5.conf

# Clean up Kerberos configuration file
RUN chmod 644 /etc/krb5.conf

CMD [ "python3","app.py" ]