FROM ubuntu:latest
LABEL version="0.0.1"
LABEL maintainer="godric.phoenix@gmail.com"
RUN apt-get update && apt-get upgrade -y
RUN apt-get install nginx -y
WORKDIR /var/www/html/
EXPOSE 80
COPY index.html index.html
CMD ["nginx","-g","daemon off;"]